### PR TITLE
fix CMakeLists.txt for OSX and Win (MSVC)

### PR DESCRIPTION
**Pull request by mtola**

### CODE REVIEW

**Comment by Pseudomanifold** [comment]
Thanks a lot for providing this patch out of the blue! I am really happy about this! One question before I merge the request, though: is it necessary to copy the Qt plugins in the build directories? This strikes me as a very odd requirement.

**Comment by mtola** [comment]
It is necessary in order to launch the .exe and has also to be done during deployment/install (not done here).

Otherwise with this CMakeLists, app compiles with 0 error and 0 warning under Linux, Mac OS X, Win and also works perfectly.

**Comment by Pseudomanifold** [comment]
Thanks for the clarification! I am merging the request and adding you as a contributor :)

**Comment by mtola** [comment]
Thanks !

**Pull request merged**
